version: '3.1'
services:
  db:
    image: mysql
    container_name: film_review_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - film_review_data:/var/lib/mysql

volumes:
  film_review_data: